[tool.poetry]
name = "package-demo"
version = "0.1.0"
description = ""
authors = ["ibrahim <ifenerci@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pendulum = "^3.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
